apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cba-static-volume
  namespace: surfer-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
