apiVersion: v1
kind: Secret
metadata:
  namespace: surfer-static
  name: your-static-users-app-only
data:
  .users.json: YOUR_B64_ENCODED_STRING_HERE
---
apiVersion: v1
kind: Secret
metadata:
  namespace: surfer-static
  name: your-static-users-with-nginx-auth
data:
  .users.json: YOUR_B64_ENCODED_STRING_HERE
  auth: YOUR_B64_ENCODED_STRING_HERE
---
apiVersion: v1
kind: Secret
metadata:
  namespace: surfer-static
  name: your-session-secret
data:
  session: YOUR_B64_ENCODED_STRING_HERE
